declare const is: <T>(type: string) => ((value: unknown) => value is T);
declare const isUndefined: (value: unknown) => value is undefined;
declare const isNull: (value: unknown) => value is null;
declare const isNullish: (value: unknown) => value is null | undefined;
declare const isDefined: <T>(value: unknown) => value is NonNullable<T>;
declare const isBoolean: (value: unknown) => value is boolean;
declare const isFalse: (value: unknown) => boolean;
declare const isFalsy: (value: unknown) => boolean;
declare const isTrue: (value: unknown) => boolean;
declare const isTruthy: (value: unknown) => boolean;
declare const isNumber: (value: unknown) => value is number;
declare const isString: (value: unknown) => value is string;
declare const isObject: (value: unknown) => value is Object;
declare const isFunction: (value: unknown) => value is Function;
declare const isInstanceOf: (constructor: typeof Element) => (value: Node) => value is Element;
declare const isElement: (node: Node) => boolean;
declare const isComment: (node: Node) => boolean;
export { is, isUndefined, isNull, isNullish, isDefined, isBoolean, isFalse, isFalsy, isTrue, isTruthy, isNumber, isString, isObject, isFunction, isInstanceOf, isElement, /* isHTMLElement, isSVGElement, isMathMLElement, */ isComment };
